// FIX: Removed self-referential import of `MessageAuthor` which caused a conflict with its own declaration.
export enum MessageAuthor {
  USER = 'user',
  BOT = 'bot',
  SYSTEM = 'system',
}

export interface FunctionCall {
  name: string;
  args: Record<string, any>;
}

export interface FunctionResponse {
  name: string;
  response: Record<string, any>;
}

export interface ChatMessage {
  author: MessageAuthor;
  text?: string;
  functionCall?: FunctionCall;
  functionResponse?: FunctionResponse;
}

export enum LLMProvider {
  GEMINI = 'gemini',
  OPENAI = 'openai',
  GROK = 'grok',
}

export type IntegrationName = 'google' | 'facebook' | 'messages';

export interface Integration {
  name: IntegrationName;
  connected: boolean;
}

// --- Profile Creation ---
export type ProfileSourceType = 'text' | 'gmail' | 'facebook';

export interface ProfileSource {
    type: ProfileSourceType;
    content?: string;
}


// --- Database Types ---

export interface User {
  id: string;
  email?: string;
  name?: string;
  avatar?: string;
  google?: {
    id: string;
    accessToken: string;
  };
  facebook?: {
    id: string;
    accessToken: string;
  };
}

export interface StyleProfile {
  id: string;
  userId: string;
  name: string;
  style: string; // The detailed style description generated by the AI
  source: ProfileSourceType;
  createdAt: string;
}

export interface License {
    id: string;
    userId: string;
    status: 'active' | 'inactive';
    createdAt: string;
    updatedAt: string;
}

export interface AuthState {
  isAuthenticated: boolean;
  user: User | null;
  license: License | null;
}

// FIX: Augment Express Request type to include properties from passport and express-session.
// This allows TypeScript to recognize `req.user`, `req.logout`, `req.isAuthenticated`, and `req.session`
// in route handlers across the application.
declare global {
  namespace Express {
    interface Request {
      user?: User;
      logout(callback: (err?: Error) => void): void;
      isAuthenticated(): boolean;
      // FIX: Removed `session?: any;` which was conflicting with the type declarations
      // from `@types/express-session`. The session is now typed by augmenting `SessionData` below.
    }

    // By augmenting SessionData, we add properties to req.session in a type-safe way
    // without conflicting with the core @types/express-session declaration.
    interface SessionData {
      activeProfileId?: string;
    }
  }
}
