// FIX: Removed self-referential import of `MessageAuthor` which caused a conflict with its own declaration.
export enum MessageAuthor {
  USER = 'user',
  BOT = 'bot',
  SYSTEM = 'system',
}

export interface FunctionCall {
  name: string;
  args: Record<string, any>;
}

export interface FunctionResponse {
  name: string;
  response: Record<string, any>;
}

export interface ChatMessage {
  author: MessageAuthor;
  text?: string;
  functionCall?: FunctionCall;
  functionResponse?: FunctionResponse;
}

export enum LLMProvider {
  GEMINI = 'gemini',
  OPENAI = 'openai',
  GROK = 'grok',
}

export type IntegrationName = 'google' | 'facebook' | 'messages';

export interface Integration {
  name: IntegrationName;
  connected: boolean;
}

export type IntegrationHealthStatus = 'connected' | 'disconnected' | 'action_required' | 'coming_soon';

export interface IntegrationSummary {
  name: IntegrationName;
  title: string;
  description: string;
  connected: boolean;
  status: IntegrationHealthStatus;
  statusMessage: string;
  sampleCount: number | null;
  lastCheckedAt: string | null;
  connectPath: string;
  docsUrl: string;
  categories: string[];
  beta?: boolean;
}

// --- Profile Creation ---
export type ProfileSourceType = 'text' | 'gmail' | 'facebook';

export interface ProfileSource {
    type: ProfileSourceType;
    content?: string;
}


// --- Database Types ---

export interface User {
  id: string;
  email?: string;
  name?: string;
  avatar?: string;
  google?: {
    id: string;
    accessToken: string;
  };
  facebook?: {
    id: string;
    accessToken: string;
  };
}

export interface StyleProfile {
  id: string;
  userId: string;
  name: string;
  style: string; // The detailed style description generated by the AI
  source: ProfileSourceType;
  createdAt: string;
}

export type ClaudeMemoryCategory = 'context' | 'style' | 'briefing';

export interface ClaudeMemorySourceArtifact {
  label: string;
  url?: string;
  excerpt?: string;
}

export interface ClaudeMemory {
  id: string;
  userId: string;
  category: ClaudeMemoryCategory;
  title: string;
  summary: string;
  highlights: string[];
  sourceArtifacts: ClaudeMemorySourceArtifact[];
  metadata?: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}

export interface License {
  id: string;
  userId: string;
  organizationId?: string;
  status: 'active' | 'inactive' | 'past_due';
  planId: string;
  trialEndsAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface BillingPlan {
  id: string;
  name: string;
  description: string;
  priceMonthly: number;
  priceYearly: number;
  pricePerSeat?: number;
  trialDays?: number;
  features: string[];
  limits: {
    monthlyMessages: number; // -1 is unlimited
    integrations: number; // -1 is unlimited
    seats: number;
  };
  isPopular?: boolean;
  meteredAddOns?: Array<{
    id: string;
    name: string;
    unitPrice: number;
    unit: string;
  }>;
}

export interface Subscription {
  id: string;
  userId: string;
  planId: string;
  status: 'trialing' | 'active' | 'past_due' | 'canceled';
  startedAt: string;
  renewsAt?: string;
  seats: number;
  customerPortalUrl?: string;
  billingEmail?: string;
  trialEndsAt?: string;
  organizationId?: string;
}

export interface UsageRecord {
  id: string;
  userId: string;
  organizationId: string;
  month: string; // YYYY-MM
  messageCount: number;
  tokenCount: number;
  lastMessageAt?: string;
}

export interface UsageSnapshot {
  organizationId: string;
  planId: string;
  monthlyLimit: number; // -1 for unlimited
  usedMessages: number;
  remainingMessages: number | 'unlimited';
  cycleRenewsAt: string;
  seats?: OrganizationSeatSnapshot;
}

export type InsightTrend = 'up' | 'down' | 'steady';

export type InsightSeverity = 'info' | 'warning' | 'critical';

export type InsightCategory = 'billing' | 'integration' | 'automation' | 'security' | 'system';

export type RecommendationPriority = 'low' | 'medium' | 'high';

export interface UsageTrendPoint {
  period: string; // YYYY-MM
  messages: number;
  tokens: number;
}

export interface PulseRecommendation {
  id: string;
  title: string;
  description: string;
  actionLabel?: string;
  actionUrl?: string;
  priority: RecommendationPriority;
}

export interface WorkspacePulse {
  organizationId: string;
  organizationName: string;
  generatedAt: string;
  billingPlan: {
    id: string;
    name: string;
    messageLimit: number | 'unlimited';
  };
  messageVelocity: {
    current: number;
    previous: number | null;
    changePercent: number | null;
    limit: number | 'unlimited';
  };
  automationQuality: {
    score: number;
    trend: InsightTrend;
    note: string;
  };
  integrationCoverage: {
    connected: number;
    total: number;
    breakdown: Array<{
      name: IntegrationName;
      connected: boolean;
      lastSyncAt: string | null;
    }>;
  };
  profileCoverage: {
    totalProfiles: number;
    activeProfiles: number;
    missingSources: ProfileSourceType[];
  };
  recommendations: PulseRecommendation[];
}

export interface IncidentInsight {
  id: string;
  timestamp: string;
  title: string;
  description: string;
  severity: InsightSeverity;
  category: InsightCategory;
  relatedId?: string;
}

export type OrganizationRole = 'owner' | 'admin' | 'author' | 'viewer';

export type OrganizationType = 'personal' | 'team';

export type SsoProvider = 'google' | 'facebook';

export type OrganizationAuthEnforcement = 'optional' | 'required';

export interface OrganizationAuthPolicy {
  enforcement: OrganizationAuthEnforcement;
  allowedProviders: SsoProvider[];
  updatedAt: string;
  updatedBy: string;
  note?: string;
}

export interface OrganizationAuthPolicyUpdate {
  enforcement: OrganizationAuthEnforcement;
  allowedProviders: SsoProvider[];
  note?: string;
}

export interface Organization {
  id: string;
  name: string;
  slug: string;
  type: OrganizationType;
  planId: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  billingEmail?: string;
  metadata?: Record<string, unknown>;
  authPolicy?: OrganizationAuthPolicy;
}

export type MembershipStatus = 'active' | 'invited' | 'suspended';

export interface Membership {
  id: string;
  organizationId: string;
  userId: string;
  role: OrganizationRole;
  status: MembershipStatus;
  invitedEmail?: string;
  invitedAt?: string;
  joinedAt?: string;
  lastActiveAt?: string;
}

export interface OrganizationSeatSnapshot {
  used: number;
  limit: number | 'unlimited';
}

export interface OrganizationSummary {
  organization: Organization;
  membership: Membership;
  seats: OrganizationSeatSnapshot;
  subscription: Subscription | null;
}

export interface OrganizationMember {
  membership: Membership;
  user: User | null;
}

export interface Invitation {
  id: string;
  organizationId: string;
  email: string;
  role: OrganizationRole;
  token: string;
  inviterId: string;
  expiresAt: string;
  status: 'pending' | 'accepted' | 'expired' | 'revoked';
  createdAt: string;
  resolvedAt?: string;
}

export type ApiScope =
  | 'chat:write'
  | 'chat:read'
  | 'profiles:read'
  | 'profiles:write'
  | 'billing:read';

export interface ApiKey {
  id: string;
  organizationId: string;
  name: string;
  prefix: string;
  hashedSecret: string;
  lastFour: string;
  scopes: ApiScope[];
  createdAt: string;
  createdBy: string;
  expiresAt?: string;
  revokedAt?: string;
  lastUsedAt?: string;
}

export interface ApiKeySummary {
  id: string;
  organizationId: string;
  name: string;
  prefix: string;
  lastFour: string;
  scopes: ApiScope[];
  createdAt: string;
  createdBy: string;
  expiresAt?: string;
  revokedAt?: string;
  lastUsedAt?: string;
}

export interface ApiKeyWithSecret {
  key: ApiKeySummary;
  secret: string;
}

export type WebhookEvent =
  | 'chat.completed'
  | 'profile.created'
  | 'profile.updated'
  | 'billing.invoice.created';

export interface WebhookSubscription {
  id: string;
  organizationId: string;
  url: string;
  events: WebhookEvent[];
  secret: string;
  secretLastFour: string;
  status: 'active' | 'paused';
  createdAt: string;
  createdBy: string;
  lastDeliveredAt?: string;
  lastFailureAt?: string;
}

export interface AuditLog {
  id: string;
  organizationId: string;
  actorId: string | null;
  action: string;
  targetType: string;
  targetId?: string;
  metadata?: Record<string, unknown>;
  createdAt: string;
}

export interface AuthState {
  isAuthenticated: boolean;
  user: User | null;
  license: License | null;
  subscription: Subscription | null;
  usage: UsageSnapshot | null;
  organizations?: OrganizationSummary[];
  activeOrganizationId?: string | null;
  invitations?: Invitation[];
}

// FIX: Augment Express Request type to include properties from passport and express-session.
// This allows TypeScript to recognize `req.user`, `req.logout`, `req.isAuthenticated`, and `req.session`
// in route handlers across the application.
declare global {
  namespace Express {
    interface Request {
      user?: User;
      logout(callback: (err?: Error) => void): void;
      isAuthenticated(): boolean;
      // FIX: Removed `session?: any;` which was conflicting with the type declarations
      // from `@types/express-session`. The session is now typed by augmenting `SessionData` below.
    }

    // By augmenting SessionData, we add properties to req.session in a type-safe way
    // without conflicting with the core @types/express-session declaration.
    interface SessionData {
      activeProfileId?: string;
      activeOrganizationId?: string;
    }
  }
}
